#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/Nexus
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: Install JRE
  become: yes
  apt:
    name: openjdk-17-jre
    state: present  
      #allow_downgrade: yes

- name: Extract the Downloaded Nexus Package
  unarchive:
    src: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
    dest: /opt
    remote_src: yes

- name: Add nexus user
  user:
    name: nexus
    state: present
    system: yes

- name: create nexus.service file
  file: 
    path: /etc/systemd/system/nexus.service
    state: touch

- name: Copy the config file to nexus.service
  copy:
    src: nexus.service
    dest: /etc/systemd/system/nexus.service

- name: Change ownership of the Nexus directory
  ansible.builtin.file:
    path: /opt/nexus-3.30.1-01
    owner: nexus
    group: nexus
    state: directory
    recurse: yes

- name: Start and Enable nexus service
  systemd:
    name: nexus.service
    state: started
    enabled: true
    daemon_reload: true
  register: result
  ignore_errors: yes  # Optional, if you want to prevent the playbook from failing on errors

- name: Show error details if nexus service failed to start
  debug:
    msg: "Nexus service failed to start. Check the status for more details: {{ result }}"
  when: result.failed

